- name: Run Pacman update on arch
  hosts: arch
  tasks:

    - name: Run upgrade
      community.general.pacman:
        update_cache: yes
        upgrade: yes
      become: true
      register: pacman

    - debug: var=pacman.stdout_lines
